from Platform.Constants.database import ENGINE_STR_TEMPLATE as ENGINE_STR_TEMPLATE_PLATFORM

LOGIN = 'postgres'
PASSWORD = 'root'
NAME = 'rs_clinic'

ENGINE_STR_TEMPLATE = ENGINE_STR_TEMPLATE_PLATFORM
