"""nullable_second_name_user

Revision ID: 08fb1a269fb8
Revises: 1488ac3708c1
Create Date: 2022-02-10 21:46:51.704523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fb1a269fb8'
down_revision = '1488ac3708c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'second_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('ix_users_second_name', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_second_name', 'users', ['second_name'], unique=False)
    op.alter_column('users', 'second_name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
