"""add_address_user

Revision ID: 4ad5007ea167
Revises: 28539e34c2ef
Create Date: 2022-02-07 23:28:54.768986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad5007ea167'
down_revision = '28539e34c2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('address', sa.Text(), nullable=True))
    op.alter_column('patients', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('patients', 'surname',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('patients', 'second_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_patients_address'), 'patients', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_address'), table_name='patients')
    op.alter_column('patients', 'second_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('patients', 'surname',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('patients', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('patients', 'address')
    # ### end Alembic commands ###
