"""add_history_object_id

Revision ID: 7562c037566b
Revises: f49176042816
Create Date: 2022-02-27 16:17:47.114974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7562c037566b'
down_revision = 'f49176042816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('user', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_history_settings_area'), 'history_settings', ['area'], unique=True)
    op.create_index(op.f('ix_history_settings_name'), 'history_settings', ['name'], unique=False)
    op.create_index(op.f('ix_history_settings_user'), 'history_settings', ['user'], unique=False)
    op.add_column('history_service', sa.Column('object_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_service', 'object_id')
    op.drop_index(op.f('ix_history_settings_user'), table_name='history_settings')
    op.drop_index(op.f('ix_history_settings_name'), table_name='history_settings')
    op.drop_index(op.f('ix_history_settings_area'), table_name='history_settings')
    op.drop_table('history_settings')
    # ### end Alembic commands ###
