"""add_operation_table

Revision ID: c37c79f50f95
Revises: 08fb1a269fb8
Create Date: 2022-02-22 20:53:29.012836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37c79f50f95'
down_revision = '08fb1a269fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('user_create_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'users', ['user_create_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'user_create_id')
    # ### end Alembic commands ###
