"""add_date_birthday_user

Revision ID: c811ccc19a7b
Revises: 20761c64da7f
Create Date: 2022-01-29 18:44:59.274856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c811ccc19a7b'
down_revision = '20761c64da7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_name'), 'settings', ['name'], unique=False)
    op.create_index(op.f('ix_settings_type'), 'settings', ['type'], unique=False)
    op.add_column('users', sa.Column('date_birthday', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'date_birthday')
    op.drop_index(op.f('ix_settings_type'), table_name='settings')
    op.drop_index(op.f('ix_settings_name'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
