"""add_history_service_table

Revision ID: f49176042816
Revises: d391eac496a7
Create Date: 2022-02-27 15:54:58.682724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49176042816'
down_revision = 'd391eac496a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_service_area'), 'history_service', ['area'], unique=False)
    op.create_index(op.f('ix_history_service_text'), 'history_service', ['text'], unique=False)
    op.create_index(op.f('ix_history_service_type'), 'history_service', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_service_type'), table_name='history_service')
    op.drop_index(op.f('ix_history_service_text'), table_name='history_service')
    op.drop_index(op.f('ix_history_service_area'), table_name='history_service')
    op.drop_table('history_service')
    # ### end Alembic commands ###
